services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web/app:/var/www/html
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakephp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql  # データ永続化